version: "3.3"

services:
  app:
    build:
      context: services/app/
      dockerfile: Dockerfile.development
    privileged: true
    env_file: .env
    volumes:
      - "./services/app:/usr/src/app:delegated"
      - "~/.bash_history:/.bash_history:delegated"
      - "~/.bashrc:/.bashrc:delegated"
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
