version: "3.3"

services:
  app:
    build:
      context: services/app/
      dockerfile: Dockerfile.development
    env_file: .env
    volumes:
      - "./services/app:/usr/src/app:delegated"
      - "~/.bash_history:/root/.bash_history:delegated"
      - "~/.bashrc:/root/.bashrc:delegated"
